### PR TITLE
[CI] FIX artifact upload + Enable SofaPython3

### PR DESCRIPTION
**Pull request by guparan**
see https://github.com/actions/upload-artifact/issues/270#issuecomment-989205389

With this PR, SoftRobots will be able to automatically generate binaries.

### CODE REVIEW

**Comment by guparan** [comment]
This is now ready for review ! :crossed_fingers:

**Review by EulalieCoevoet — APPROVED** [review]
The "setup SOFA and environment" failed on Windows :(

**Comment by EulalieCoevoet** [comment]
Okay it seems to work perfectly now! Thanks Guillaume. Should I merge?

**Comment by guparan** [comment]
Something was missing, it came to my mind with my breakfast coffee :coffee: 
Will do a new PR :+1:

**Pull request merged**
