### PR TITLE
Move examples from docs/sofapython3 to ./examples

### PR DESCRIPTION
**Pull request by alxbilger**
This is to comply with the usual SOFA architecture. It is the way to do if we want the SOFA CI to execute the scenes. See https://github.com/sofa-framework/sofa/pull/3882

### CODE REVIEW

**Comment by alxbilger** [comment]
Is it possible that scenes from tutorials have a dependency to something in the `examples` folder? It would break things

**Comment by EulalieCoevoet** [comment]
I think it should be fine, but I would move the whole "sofapython3" directory from "docs" to "examples" ?

**Comment by EulalieCoevoet** [comment]
Looks good to me. Thanks.

**Comment by alxbilger** [comment]
@EulalieCoevoet thanks for the added changes. Are we ready to merge?

**Pull request merged**
