### PR TITLE
[tests] fixed tests

### PR DESCRIPTION
**Pull request by EulalieCoevoet**
Changes: 

1. Fixed engine tests 
2. Now plugin SofaSparseSolver is automatically added with the plugin
3. Fixed constraint tests (related to missing SparseLDLSolver)

Questions: 

Is it okay to force the loading of the plugin SofaSparseSolver like that?

### CODE REVIEW

**Comment by damienmarchal** [comment]
Hello Eulalie,

The general pattern for inter-module/plugin dependencies is to make the dependency explicit 
with the find_package() macros. Not doing so will result in problems while compiling the plugins out-of-tree. 

This find_package should be at the lowest possible level in the CMakeLists.txt hierarchy so if it is only needed for the tests then it should be in the test's CMakeLists.txt. 

Eg:
```
find_package(SofaSparseSolver REQUIRED)
```
Or
```
find_package(SofaSparseSolver QUIET)
if(!SofaSparseSolver_FOUND)
        message("To activate the tests you need to have the plugin SofaSparseSolver enabled")
        return() 
endif()
```

Appart from that is the automagically setting to 'ON' the plugin it depend's on...I feel a bit unsure as this is the way to go as when the plugin will be unchecked in the build system it will continue building the dependencies.

**Comment by EulalieCoevoet** [comment]
Hi,

Thanks for the quick reply. As all the scenes in the plugin (tests but also examples...) require this plugin to be compiled, I think I will go for:

`find_package(SofaSparseSolver REQUIRED)`

In the main CMakeLists.tkt...
Mainly because I know that people doesn't read cmake messages if they are not errors... and I don't like the idea of having all the examples failling...

**Comment by EulalieCoevoet** [comment]
I think it's okay like that.  
@damienmarchal Should we merge or do you see something wrong?

**Comment by damienmarchal** [comment]
I see there is no find_package is this on purpose ?

**Pull request merged**
