### PR TITLE
[tutorials] Tripod: cleaning

### PR DESCRIPTION
**Pull request by EulalieCoevoet**
Mainly warnings cleaning:
-  SceneCheckMissingRequiredPlugin
-  SceneCheckDuplicatedName
- `UniformMass` initialisation
-  adds a new requirement to the doc 
-  typos
-  UncoupledConstraintCorrection compliance warning

### CODE REVIEW

**Comment by olivier-roussel** [comment]
Tested in a conda environment with latest SOFA master successfully until step7, where I guess I need a robot to plug
```
[ERROR]   [stlib3.interface.serialport] No serial port found with manufacturer = Arduino
```
Is that the expected behavior ?

I will try to build conda packages from this to perform a test from a SOFA installation fully from conda packages in a second step.

**Comment by EulalieCoevoet** [comment]
Yes, because in step7 we connect the robot to the simulation. 
However this code has never been tested on Windows and MacOS... I only tested it on Linux.

**Comment by olivier-roussel** [comment]
Tested successfully all steps now (thanks to your support @EulalieCoevoet). 
Looks good to me.

**Comment by damienmarchal** [comment]
So do we merge ?

**Comment by olivier-roussel** [comment]
I guess we should (on my side I can't I have no merge rights).

**Pull request merged**
