### PR TITLE
[SoftRobots] Refactor plugin sources

### PR DESCRIPTION
**Pull request by marques-bruno**
Code refactor to comply with SOFA's plugin repository structure:

Let's be careful when merging: all the c++ sources have been moved, so conflicts will show up on your local modifications

### CODE REVIEW

**Comment by damienmarchal** [comment]
To me this should be done... I let eulalie merge.

**Comment by marques-bruno** [comment]
[ci-build]

**Comment by marques-bruno** [comment]
[ci-build]

**Comment by marques-bruno** [comment]
@EulalieCoevoet This PR restores the tests... but the test fails & segfaults:
https://ci.inria.fr/defrost-ci/job/SoftRobots_PR/5/console
Any idea? :/

**Comment by EulalieCoevoet** [comment]
The tests need the module containing SparseLDLSolver.

**Comment by EulalieCoevoet** [comment]
Otherwise I'm okay to merge, thanks a lot Bruno!

**Pull request merged**
