### PR TITLE
Fix constraint violation

### PR DESCRIPTION
**Pull request by EulalieCoevoet**
Changed how the constraint violation is computed.

### CODE REVIEW

**Comment by damienmarchal** [comment]
@marques-bruno Is there really tests executed on the CI ? I'm not sure. Can you check that plz ?

**Comment by marques-bruno** [comment]
> @marques-bruno Is there really tests executed on the CI ? I'm not sure. Can you check that plz ?

Hi @damienmarchal, no there's no test on the CI. The ci script is set to compile tests by looking for executable files in bin/ that are suffixed with "_test" and runs any it finds. Results are displayed in the github notification as <nb_of_failed_tests>/<total_nb_tests>, hence the "0/0 tests failed" message.
I can customize the ci script further to avoid confusion by adding a "no tests for this project" message or something like this if you want

**Comment by damienmarchal** [comment]
Thanks for the answer, 
but as there is tests in SoftRobots I still don't understand the 0/0

**Comment by marques-bruno** [comment]
I see....
I'll investigate

**Comment by marques-bruno** [comment]
It seems that:
1. SOFA_BUILD_TESTS, just like PLUGIN_SOFAPYTHON and SOFA_BUILD_METIS, are not exported as CMake variables in the targets. out-of-tree builds have to set those manually.
2. Also, the SoftRobots plugin does not respect the SOFA plugin filesystem hierarchy (<repo_root>/src/SoftRobots>) which leads to header inclusion errors in the tests when cloning SoftRobots in a different directory name (as it is the case on the CI, with SoftRobots_PR and SoftRobots_master depending on the job...).

I temporaily fixed the first problem by adding the SOFA_BUILD_TESTS variable in the out-of-tree build, although the appropriate fix would be to fix it in the SOFA targets. I'll make a SOFA PR later on.
As for the 2nd issue, it requires moving files around using git mv, so I'll wait for your input @damienmarchal

**Comment by damienmarchal** [comment]
I fully support the idea of using the Sofa way of organizing file in the plugin for proper packaging. I think the plugin was designed before this decision was taken in Sofa...so we may fix that with a PR, we just need a bit synchronisation with @EulalieCoevoet  to minimize the surprised (or conflict with existing branches).

**Comment by EulalieCoevoet** [comment]
Okay, I didn't notice the new filesystem hierarchy.

**Comment by damienmarchal** [comment]
Hi all,

In this PR some tests are still failing.

**Comment by EulalieCoevoet** [comment]
It's still the problem of running the tests with the module SofaSparseSolver enabled

`[ERROR]   [RequiredPlugin(requiredPlugin2)]  failed to load: SofaSparseSolver`

**Comment by EulalieCoevoet** [comment]
This PR fix several things, I think it's time to merge.

**Comment by damienmarchal** [comment]
Hi Eulalie,

Thank for the work done. This is far from what I understand so I trust you that the PR does not break anything :) 


In the code there is a lot of sequence of getValue()
```cpp
    Coord p0 = x[d_indices.getValue()[0]];
    Coord p3 = xfree.getValue()[d_indices.getValue()[3]];
    Coord p1 = x[d_indices.getValue()[1]];
    Coord p2 = x[d_indices.getValue()[2]];
    Coord p3 = x[d_indices.getValue()[3]];
```

These should be replaced with Read/WriteAccessor. The problem with a single getValue is that it contains a begin/endEdit pair which force a resynchronisation of the data from its connected data (parent data or data engine). In addition.... you cannot make the assumption that the data has not changed  (by a different thread) between two getValue while you can do such assumption if you have a begin/end pair.

**Pull request merged**
